#:import dp kivy.metrics.dp

<Toolbar>:

    size_hint_y: None
    height: dp(46)

    spacing: dp(6)
    padding: dp(6)

    Button:
        text: "Open"
        on_release: root.open_clicked()

    Button:
        text: "Save"
        on_release: root.save_clicked()

    Button:
        text: "Reload"
        on_release: root.reload_clicked()

    Button:
        text: "Close"
        on_release: root.close_clicked()